---
- name: Cau hinh tren router
  hosts: SW1
  gather_facts: no

  tasks:
    - name: Show ip
      ios_command:
        commands:
          - show ip inter br
      register: output

    - debug: var=output.stdout_lines
